version: '3'

services:

    frontend:
        container_name: front
        image: bryaalbani/app_backend:latest
        ports:
            - "3000:3000"
    backend:
        container_name: back
        image: bryaalbani/app_frontend:latest
        ports:
            - "8080:8080"
        environment:
            - AWS_BUCKET_NAME=bryaalbani
            - AWS_BUCKET_REGION=us-east-1
            - AWS_ACCESS_KEY=AKIAXBDX4GV6KNZC7XFX
            - AWS_SECRET_KEY=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
        depends_on:
            - frontend
       
        
        
